name: graphics
version: 0.1.0.0
github: "aronerben/graphics"
license: BSD3
author: "Aron Erben"
maintainer: "aron.erben@gmail.com"
copyright: "2021 Aron Erben"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aronerben/graphics#readme>

dependencies:
  - base >= 4.7 && < 5
  - matrix
  - vector

library:
  source-dirs: src

executables:
  graphics-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - graphics

tests:
  graphics-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - graphics
